name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build-api:
    name: build-api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
      with:
        images: rasmus256docker/optimalpowertimecalculator
        tags: |
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        # Username used to log against the Docker registry
        username: rasmus256docker
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
      with:
        file: src/api/Dockerfile
        context: src
        push: false
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
    - uses: kitabisa/docker-slim-action@6a9a64eaf0c08b1251c148514dd70be1495bff12 # v1.2.0
      env:
        DSLIM_HTTP_PROBE: false
      with:
        target: ${{ github.repository }}:latest
        tag: "slim"

    # Push to the registry
    - run: docker image push "${{ github.repository }}:latest" --all-tags
