name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build-api:
    name: build-api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
      with:
        images: rasmus256docker/optimalpowertimecalculator
        tags: |
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        # Username used to log against the Docker registry
        username: rasmus256docker
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    - uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
      with:
        file: src/api/Dockerfile
        context: src
        push: false
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
    - uses: kitabisa/docker-slim-action@6a9a64eaf0c08b1251c148514dd70be1495bff12 # v1.2.0
      env:
        DSLIM_HTTP_PROBE: false
      with:
        target: ${{ github.repository }}:latest
        tag: "slim"

    # Push to the registry
    - run: docker image push "${{ github.repository }}:latest" --all-tags
