name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -f src/api/Dockerfile -t optimal-power-calculator .

    - name: Run tests in Docker
      run: |
        docker run --rm optimal-power-calculator python -m pytest -v --tb=short --disable-warnings
